---
title: "City Guide to Hamburg and Rotterdam"
author: Lea Schumacher
theme: Yeti
format: html
editor: visual
---

Welcome! This is a city guide to Hamburg and Rotterdam.

# Cozy cafés in Hamburg

-   \[Paledo\] (https://paledohamburg.de): has great food and coffee. Based in Winterhude, Eppendorf and Rotherbaum.

# Fun outdoor activities in Hamburg

-   Biking along the Elbe to Blankenese
-   Taking a ferry to Finkenwerder to enjoy the river cruise. No additional costs if you own a HVV ticket.

# Best water activities in Hamburg

-   Elbstrand
-   Stand-up paddling on the Alster canals

# Best cinemas in Hamburg

-   [Abaton Kino](https://www.abaton.de/page.pl?index)
-   [Passage-Kino](https://www.das-passage.de)

# Ideal places for a fun night out in Hamburg

-   Christmas market Santa Pauli

# Places to avoid in Hamburg

-   Espresso house, not cozy, bad coffee going out to welllness sauna really comes you down in Hamburg

# Places to relax in Hamburg

-   Shopping in the Europa passage, sitting at starbucks coffeeshop there
-   Visiting a Spa
